image: Visual Studio 2017
branches:
  only:
    - master
    - develop
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
build_script:
- cmd: powershell -Command .\build.ps1
test_script:
- cmd: echo noop
after_test:
- cmd: echo noop
